### ISSUE TITLE
Map Locations a not working

### ISSUE THREAD

**Issue by SebastianH17** [Kalnix/dark-archives-map-remake-by-kalnix#1]
Lovely maps thanks for taking the time, however importing it on V10 causes the following issue.

The background maps point to this file path

**DarkArchive/The_Beast_Of_Birchfront_Map_1.webp**

which does not seem to get created by the import.

Manually fixing it to point to the actual module like 

**modules/dark-archives-map-remakes-by-kalnix/maps/The_Beast_Of_Birchfront_Map_1.webp**

fixes things.
Thank you for taking the time to make these and share them with the community.

**Comment by Kalnix** [comment]
Good catch, seems I forgot to change the filepaths to the maps to be the ones in the module before uploading. This should be fixed now as I have fixed the filepaths and confirmed that a fresh install does point to the right location. Thanks for pointing this out!
